server:
  port: 9000
spring:
  application:
    name: matt-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true # 请求服务是小写的时候改成true（默认为false轻微服务必须是大写）
      routes:
        - id: order_routh
          uri: lb://matt-order  # 服务端 service_id
          predicates:
            - Path=/order/**         # 断言，路径相匹配的进行路由
            - Cookie=username,66lai66
